/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 3
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

        preprocess:
            lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for any other pointcloud input
            scan_line:  8
            # Minimum valid range in meters.
            # Balance between self-body reflections and near obstacle visibility.
            blind: 0.25
            timestamp_unit: 3
            scan_rate: 10

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     100.0
            extrinsic_est_en:  false     # Use calibrated fixed extrinsic
            # From calibration: roll=0.0 deg, pitch=19.0 deg, yaw=1.0 deg, x/y/z=-100/0/-26 cm
            extrinsic_T: [ 0.0, 0.0, -0.26 ]
            extrinsic_R: [ 0.945374569, -0.017452406, 0.325518569,
                           0.016501574, 0.999847695, 0.005681948,
                           -0.325568154, 0.0, 0.945518576 ]

        publish:
            path_en: true                # true: publish Path
            effect_map_en: false         # true: publish Effects
            map_en: true                 # true: publish Map cloud
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # true: keep denser cloud for reliable near obstacle projection to LaserScan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
            tf_en: true

        pcd_save:
            pcd_save_en: true
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
