#!/usr/bin/env python3

import math
import os
from typing import Optional

import rclpy
from rclpy.executors import ExternalShutdownException
from rclpy.node import Node
from rclpy.qos import qos_profile_sensor_data
from sensor_msgs.msg import Imu, NavSatFix


def yaw_from_quaternion(q) -> float:
    siny_cosp = 2.0 * (q.w * q.z + q.x * q.y)
    cosy_cosp = 1.0 - 2.0 * (q.y * q.y + q.z * q.z)
    return math.atan2(siny_cosp, cosy_cosp)


def normalize_angle(angle: float) -> float:
    return math.atan2(math.sin(angle), math.cos(angle))


class MapOriginRecorder(Node):
    def __init__(self) -> None:
        super().__init__("map_origin_recorder")

        self.declare_parameter("fix_topic", "/rtk/fix")
        self.declare_parameter("heading_topic", "/rtk/navsat_heading")
        self.declare_parameter("output_path", "/tmp/rtk_map_origin.yaml")
        self.declare_parameter("frame_id", "map")
        self.declare_parameter("require_heading", True)
        self.declare_parameter("heading_yaw_offset", 0.0)
        self.declare_parameter("overwrite", False)

        self.fix_topic = str(self.get_parameter("fix_topic").value)
        self.heading_topic = str(self.get_parameter("heading_topic").value)
        self.output_path = os.path.expanduser(str(self.get_parameter("output_path").value))
        self.frame_id = str(self.get_parameter("frame_id").value)
        self.require_heading = bool(self.get_parameter("require_heading").value)
        self.heading_yaw_offset = float(self.get_parameter("heading_yaw_offset").value)
        self.overwrite = bool(self.get_parameter("overwrite").value)

        self.latest_fix: Optional[NavSatFix] = None
        self.latest_yaw: Optional[float] = None
        self.recorded = False

        self.fix_subscription = self.create_subscription(
            NavSatFix, self.fix_topic, self._fix_callback, qos_profile_sensor_data
        )
        self.heading_subscription = self.create_subscription(
            Imu, self.heading_topic, self._heading_callback, qos_profile_sensor_data
        )

        self.get_logger().info(
            "Map origin recorder started: "
            f"fix={self.fix_topic}, heading={self.heading_topic}, output={self.output_path}, "
            f"require_heading={self.require_heading}, overwrite={self.overwrite}"
        )

    def _heading_callback(self, msg: Imu) -> None:
        self.latest_yaw = normalize_angle(
            yaw_from_quaternion(msg.orientation) + self.heading_yaw_offset
        )
        self._try_record()

    def _fix_callback(self, msg: NavSatFix) -> None:
        self.latest_fix = msg
        self._try_record()

    def _try_record(self) -> None:
        if self.recorded or self.latest_fix is None:
            return
        if self.require_heading and self.latest_yaw is None:
            return
        if os.path.exists(self.output_path) and not self.overwrite:
            self.get_logger().error(
                f"Map origin file already exists and overwrite=false: {self.output_path}"
            )
            self.recorded = True
            return

        yaw = self.latest_yaw if self.latest_yaw is not None else 0.0
        directory = os.path.dirname(self.output_path)
        if directory:
            os.makedirs(directory, exist_ok=True)

        stamp = self.latest_fix.header.stamp
        content = (
            "# Generated by map_origin_recorder.py\n"
            "# yaw_enu follows ROS REP-103/robot_localization convention: 0=east, CCW positive.\n"
            f"frame_id: {self.frame_id}\n"
            f"latitude: {self.latest_fix.latitude:.12f}\n"
            f"longitude: {self.latest_fix.longitude:.12f}\n"
            f"altitude: {self.latest_fix.altitude:.6f}\n"
            f"yaw_enu: {yaw:.12f}\n"
            f"stamp_sec: {stamp.sec}\n"
            f"stamp_nanosec: {stamp.nanosec}\n"
        )
        with open(self.output_path, "w", encoding="utf-8") as output:
            output.write(content)

        self.recorded = True
        self.get_logger().info(
            "Recorded map origin: "
            f"lat={self.latest_fix.latitude:.9f}, lon={self.latest_fix.longitude:.9f}, "
            f"alt={self.latest_fix.altitude:.3f}, yaw_enu={yaw:.6f}, path={self.output_path}"
        )


def main(args=None) -> None:
    rclpy.init(args=args)
    node = MapOriginRecorder()
    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, ExternalShutdownException):
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
